[2024-07-12T00:06:53.272+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data-ingestion.ingest_task manual__2024-07-12T00:01:49.433375+00:00 [queued]>
[2024-07-12T00:06:53.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data-ingestion.ingest_task manual__2024-07-12T00:01:49.433375+00:00 [queued]>
[2024-07-12T00:06:53.277+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-12T00:06:53.283+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonVirtualenvOperator): ingest_task> on 2024-07-12 00:01:49.433375+00:00
[2024-07-12T00:06:53.287+0000] {standard_task_runner.py:60} INFO - Started process 195 to run task
[2024-07-12T00:06:53.290+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data-ingestion', 'ingest_task', 'manual__2024-07-12T00:01:49.433375+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion.py', '--cfg-path', '/tmp/tmpxoix728h']
[2024-07-12T00:06:53.291+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask ingest_task
[2024-07-12T00:06:53.310+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-12T00:06:53.327+0000] {task_command.py:423} INFO - Running <TaskInstance: data-ingestion.ingest_task manual__2024-07-12T00:01:49.433375+00:00 [running]> on host ***-scheduler
[2024-07-12T00:06:53.358+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data-ingestion' AIRFLOW_CTX_TASK_ID='ingest_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:01:49.433375+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T00:01:49.433375+00:00'
[2024-07-12T00:06:54.236+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvy0fu7wge --system-site-packages --python=python
[2024-07-12T00:06:54.252+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:06:54.550+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.19.final.0-64 in 100ms
[2024-07-12T00:06:54.550+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvy0fu7wge, clear=False, no_vcs_ignore=False, global=True)
[2024-07-12T00:06:54.551+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-07-12T00:06:54.551+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.0, setuptools==69.1.0, wheel==0.42.0
[2024-07-12T00:06:54.551+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-07-12T00:06:54.572+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy0fu7wge/bin/pip install -r /tmp/venvy0fu7wge/requirements.txt
[2024-07-12T00:06:54.576+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:06:55.571+0000] {process_utils.py:190} INFO - Collecting acryl-datahub==0.12.1.5 (from -r /tmp/venvy0fu7wge/requirements.txt (line 1))
[2024-07-12T00:06:55.615+0000] {process_utils.py:190} INFO -   Downloading acryl_datahub-0.12.1.5-py3-none-any.whl.metadata (138 kB)
[2024-07-12T00:06:55.636+0000] {process_utils.py:190} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 kB 8.1 MB/s eta 0:00:00
[2024-07-12T00:06:57.669+0000] {process_utils.py:190} INFO - Requirement already satisfied: tabulate in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.9.0)
[2024-07-12T00:06:57.670+0000] {process_utils.py:190} INFO - Requirement already satisfied: progressbar2 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (4.4.2)
[2024-07-12T00:06:57.671+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.0.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.4.0)
[2024-07-12T00:06:57.671+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonref in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.1.0)
[2024-07-12T00:06:57.671+0000] {process_utils.py:190} INFO - Requirement already satisfied: psutil>=5.8.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (5.9.8)
[2024-07-12T00:06:57.671+0000] {process_utils.py:190} INFO - Requirement already satisfied: Deprecated in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.2.14)
[2024-07-12T00:06:57.672+0000] {process_utils.py:190} INFO - Requirement already satisfied: cached-property in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.5.2)
[2024-07-12T00:06:57.672+0000] {process_utils.py:190} INFO - Requirement already satisfied: PyYAML in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (6.0.1)
[2024-07-12T00:06:57.672+0000] {process_utils.py:190} INFO - Requirement already satisfied: pydantic!=1.10.3,>=1.10.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.8.2)
[2024-07-12T00:06:57.672+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-file in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.1.0)
[2024-07-12T00:06:57.673+0000] {process_utils.py:190} INFO - Requirement already satisfied: avro<1.12,>=1.11.3 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.11.3)
[2024-07-12T00:06:57.673+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (24.0)
[2024-07-12T00:06:57.673+0000] {process_utils.py:190} INFO - Requirement already satisfied: ijson in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.2.3)
[2024-07-12T00:06:57.673+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (7.0.0)
[2024-07-12T00:06:57.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: sentry-sdk in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.9.0)
[2024-07-12T00:06:57.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: click-spinner in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.1.10)
[2024-07-12T00:06:57.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: mixpanel>=4.9.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (4.10.1)
[2024-07-12T00:06:57.674+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-inspect in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.9.0)
[2024-07-12T00:06:57.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: toml>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.10.2)
[2024-07-12T00:06:57.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: click>=7.1.2 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (8.1.7)
[2024-07-12T00:06:57.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.9.0.post0)
[2024-07-12T00:06:57.675+0000] {process_utils.py:190} INFO - Requirement already satisfied: humanfriendly in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (10.0)
[2024-07-12T00:06:57.676+0000] {process_utils.py:190} INFO - Requirement already satisfied: click-default-group in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.2.4)
[2024-07-12T00:06:57.676+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (4.10.0)
[2024-07-12T00:06:57.676+0000] {process_utils.py:190} INFO - Requirement already satisfied: expandvars>=0.6.5 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.12.0)
[2024-07-12T00:06:57.676+0000] {process_utils.py:190} INFO - Requirement already satisfied: aiohttp<4 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.9.3)
[2024-07-12T00:06:57.677+0000] {process_utils.py:190} INFO - Requirement already satisfied: ruamel.yaml in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.18.6)
[2024-07-12T00:06:57.677+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonschema in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (4.21.1)
[2024-07-12T00:06:57.910+0000] {process_utils.py:190} INFO - Collecting avro-gen3==0.7.11 (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1))
[2024-07-12T00:06:57.920+0000] {process_utils.py:190} INFO -   Downloading avro_gen3-0.7.11-py3-none-any.whl.metadata (8.3 kB)
[2024-07-12T00:06:57.926+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (6.11.0)
[2024-07-12T00:06:57.929+0000] {process_utils.py:190} INFO - Requirement already satisfied: six in /home/***/.local/lib/python3.8/site-packages (from avro-gen3==0.7.11->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.16.0)
[2024-07-12T00:06:57.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: aiosignal>=1.1.2 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.3.1)
[2024-07-12T00:06:57.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: attrs>=17.3.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (23.2.0)
[2024-07-12T00:06:57.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: frozenlist>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.4.1)
[2024-07-12T00:06:57.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: multidict<7.0,>=4.5 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (6.0.5)
[2024-07-12T00:06:57.938+0000] {process_utils.py:190} INFO - Requirement already satisfied: yarl<2.0,>=1.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.9.4)
[2024-07-12T00:06:57.939+0000] {process_utils.py:190} INFO - Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/***/.local/lib/python3.8/site-packages (from aiohttp<4->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (4.0.3)
[2024-07-12T00:06:57.956+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata>=4.0.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.18.1)
[2024-07-12T00:06:57.958+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests>=2.4.2 in /home/***/.local/lib/python3.8/site-packages (from mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.31.0)
[2024-07-12T00:06:57.958+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.26.18)
[2024-07-12T00:06:57.968+0000] {process_utils.py:190} INFO - Requirement already satisfied: annotated-types>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from pydantic!=1.10.3,>=1.10.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.7.0)
[2024-07-12T00:06:57.968+0000] {process_utils.py:190} INFO - Requirement already satisfied: pydantic-core==2.20.1 in /home/***/.local/lib/python3.8/site-packages (from pydantic!=1.10.3,>=1.10.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2.20.1)
[2024-07-12T00:06:57.981+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from Deprecated->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.16.0)
[2024-07-12T00:06:57.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (5.13.0)
[2024-07-12T00:06:57.999+0000] {process_utils.py:190} INFO - Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2023.12.1)
[2024-07-12T00:06:57.999+0000] {process_utils.py:190} INFO - Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.3.10)
[2024-07-12T00:06:58.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: referencing>=0.28.4 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.34.0)
[2024-07-12T00:06:58.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: rpds-py>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from jsonschema->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.18.0)
[2024-07-12T00:06:58.005+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-utils>=3.8.1 in /home/***/.local/lib/python3.8/site-packages (from progressbar2->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.8.2)
[2024-07-12T00:06:58.011+0000] {process_utils.py:190} INFO - Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /home/***/.local/lib/python3.8/site-packages (from ruamel.yaml->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (0.2.8)
[2024-07-12T00:06:58.053+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from sentry-sdk->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (2024.2.2)
[2024-07-12T00:06:58.057+0000] {process_utils.py:190} INFO - Requirement already satisfied: mypy-extensions>=0.3.0 in /home/***/.local/lib/python3.8/site-packages (from typing-inspect->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (1.0.0)
[2024-07-12T00:06:58.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.4.2->mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.3.2)
[2024-07-12T00:06:58.096+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.4.2->mixpanel>=4.9.0->acryl-datahub==0.12.1.5->-r /tmp/venvy0fu7wge/requirements.txt (line 1)) (3.6)
[2024-07-12T00:06:58.177+0000] {process_utils.py:190} INFO - Downloading acryl_datahub-0.12.1.5-py3-none-any.whl (1.6 MB)
[2024-07-12T00:06:58.267+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.7 MB/s eta 0:00:00
[2024-07-12T00:06:58.274+0000] {process_utils.py:190} INFO - Downloading avro_gen3-0.7.11-py3-none-any.whl (26 kB)
[2024-07-12T00:07:03.827+0000] {process_utils.py:190} INFO - Installing collected packages: avro-gen3, acryl-datahub
[2024-07-12T00:07:03.828+0000] {process_utils.py:190} INFO -   Attempting uninstall: avro-gen3
[2024-07-12T00:07:03.829+0000] {process_utils.py:190} INFO -     Found existing installation: avro-gen3 0.7.13
[2024-07-12T00:07:03.829+0000] {process_utils.py:190} INFO -     Not uninstalling avro-gen3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy0fu7wge
[2024-07-12T00:07:03.830+0000] {process_utils.py:190} INFO -     Can't uninstall 'avro-gen3'. No files were found to uninstall.
[2024-07-12T00:07:03.853+0000] {process_utils.py:190} INFO -   Attempting uninstall: acryl-datahub
[2024-07-12T00:07:03.860+0000] {process_utils.py:190} INFO -     Found existing installation: acryl-datahub 0.13.3.2
[2024-07-12T00:07:03.860+0000] {process_utils.py:190} INFO -     Not uninstalling acryl-datahub at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvy0fu7wge
[2024-07-12T00:07:03.861+0000] {process_utils.py:190} INFO -     Can't uninstall 'acryl-datahub'. No files were found to uninstall.
[2024-07-12T00:07:04.544+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-07-12T00:07:04.544+0000] {process_utils.py:190} INFO - acryl-datahub-***-plugin 0.13.3.2 requires acryl-datahub[datahub-rest]==0.13.3.2, but you have acryl-datahub 0.12.1.5 which is incompatible.
[2024-07-12T00:07:04.545+0000] {process_utils.py:190} INFO - Successfully installed acryl-datahub-0.12.1.5 avro-gen3-0.7.11
[2024-07-12T00:07:04.614+0000] {process_utils.py:190} INFO - 
[2024-07-12T00:07:04.614+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.0 -> 24.1.2
[2024-07-12T00:07:04.614+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-07-12T00:07:04.784+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvy0fu7wge/bin/python /tmp/venv-callscnua70o/script.py /tmp/venv-callscnua70o/script.in /tmp/venv-callscnua70o/script.out /tmp/venv-callscnua70o/string_args.txt /tmp/venv-callscnua70o/termination.log
[2024-07-12T00:07:04.788+0000] {process_utils.py:186} INFO - Output:
[2024-07-12T00:07:04.800+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callscnua70o/script.py", line 49
[2024-07-12T00:07:04.800+0000] {process_utils.py:190} INFO -     unusual_prefix_50923f202a1be2ffe879bd287c2681623b93c2bb_data-ingestion  = types.ModuleType("unusual_prefix_50923f202a1be2ffe879bd287c2681623b93c2bb_data-ingestion")
[2024-07-12T00:07:04.801+0000] {process_utils.py:190} INFO -     ^
[2024-07-12T00:07:04.801+0000] {process_utils.py:190} INFO - SyntaxError: cannot assign to operator
[2024-07-12T00:07:04.975+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 401, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 723, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 461, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 171, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/process_utils.py", line 194, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvy0fu7wge/bin/python', '/tmp/venv-callscnua70o/script.py', '/tmp/venv-callscnua70o/script.in', '/tmp/venv-callscnua70o/script.out', '/tmp/venv-callscnua70o/string_args.txt', '/tmp/venv-callscnua70o/termination.log']' returned non-zero exit status 1.
[2024-07-12T00:07:05.001+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data-ingestion, task_id=ingest_task, execution_date=20240712T000149, start_date=20240712T000653, end_date=20240712T000704
[2024-07-12T00:07:05.016+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task ingest_task (Command '['/tmp/venvy0fu7wge/bin/python', '/tmp/venv-callscnua70o/script.py', '/tmp/venv-callscnua70o/script.in', '/tmp/venv-callscnua70o/script.out', '/tmp/venv-callscnua70o/string_args.txt', '/tmp/venv-callscnua70o/termination.log']' returned non-zero exit status 1.; 195)
[2024-07-12T00:07:05.065+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-12T00:07:05.076+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
